"""Agent-friendly roadmap tool: a short brief to read, and commands for the routine edits.

    python scripts/roadmap.py brief                  # write docs/roadmap/roadmap-brief.md and print it
    python scripts/roadmap.py start M10.3            # task -> doing
    python scripts/roadmap.py done M10.3 --refs a,b --note "..." --title "Release name" --text "One sentence." --highways engine,tooling
    python scripts/roadmap.py log "What changed and why."
    python scripts/roadmap.py add-task M10 --area engine --title "..." --note "..."

roadmap.js is huge, so agents should not open it. Every edit changes only the lines it needs (so diffs stay small),
re-runs check_roadmap, and puts the file back if the check fails.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

from check_roadmap import ROADMAP, check, load

BRIEF = ROADMAP.with_name("roadmap-brief.md")
OPEN = ("doing", "next", "blocked", "todo")


def vkey(version: str) -> tuple[int, ...]:
    return tuple(int(p) for p in version.split("."))


def clip(text: str, n: int) -> str:
    text = " ".join(str(text).split())
    return text if len(text) <= n else text[: n - 1].rstrip() + "…"


# ---------------------------------------------------------------- brief


def build_brief(data: dict) -> str:
    releases = data["releases"]
    released = [r for r in releases if r["status"] == "released"]
    latest = released[-1]["version"] if released else "none"
    nxt = next((r for r in releases if r["status"] == "next"), None)
    lines = [
        "# Completionist roadmap brief",
        "",
        "Generated by `python scripts/roadmap.py brief`. Do not edit, and do not commit.",
        "**Avoid opening `docs/roadmap/roadmap.js` (thousands of lines).** Read this brief, and change the roadmap with",
        "`python scripts/roadmap.py start|done|log|add-task` (see the end). Open `roadmap.js` only for what those can't do",
        "(dropping or moving tasks, release essays, decisions, risks), and then read just the part you need.",
        "",
        f"- Updated {data['updated']}. Latest release **{latest}**."
        + (f" Next release **{nxt['version']}**: {nxt['title']}." if nxt else ""),
        f"- Now: {data.get('now', '')}",
        "",
    ]

    lines += ["## Highways and task areas", ""]
    lines += [f"- `{h['id']}` ({h['title']}): areas {', '.join(h['areas'])}" + (f"; opens {h['opens']}" if h.get("opens") else "")
              for h in data["highways"]]

    groups = [m for m in data["milestones"] if m["status"] != "done"]
    groups.sort(key=lambda m: (m["status"] != "active", ))
    for m in groups:
        release = next((r["version"] for r in releases if r.get("milestone") == m["id"]), "?")
        tasks = m["tasks"]
        done = sum(t["status"] == "done" for t in tasks)
        lines += ["", f"## {m['status'].upper()}: {m['id']} → {release} · {m['title']} ({done}/{len(tasks)} done)", "",
                  f"Goal: {m['goal']}", f"Done when: {m['done_when']}", ""]
        for t in sorted(tasks, key=lambda t: vkey(t["version"])):
            if t["status"] == "done":
                continue
            note = f" — {clip(t['notes'], 200)}" if t.get("notes") and t["status"] != "dropped" else ""
            lines.append(f"- [{t['status']}] {t['id']} · {t['version']} · {t['area']} · {t['title']}{note}")

    open_risks = [r for r in data["risks"] if r["status"] == "open"]
    if open_risks:
        lines += ["", "## Open risks", ""] + [f"- {clip(r['text'], 220)}" for r in open_risks]

    lines += ["", "## Recent decisions (newest first)", ""]
    lines += [f"- {d['date']}: {clip(d['text'], 260)}" for d in data["decisions"][:5]]
    lines += ["", "## Recent log (newest first)", ""]
    lines += [f"- {e['date']}: {clip(e['text'], 220)}" for e in data["log"][:6]]

    lines += [
        "", "## Rules you need", "",
        "- Every task has its own patch version; finishing it adds a `released` patch entry. `done` does this for you.",
        "- Every commit stages `roadmap.js` with a new top `log` line (`log` does this) and `python scripts/check_roadmap.py` must print `roadmap ok`.",
        "- When a group's last task is done: set the group to `done` and its finish-line release to `released` by hand in `roadmap.js`.",
        "", "## Commands", "",
        "- `python scripts/roadmap.py start <task>`: status `doing`.",
        "- `python scripts/roadmap.py done <task> --title \"Release name\" --text \"One sentence, under 50 words.\" --highways engine,tooling [--refs a,b] [--note \"...\"]`:",
        "  status `done`, adds the patch release, promotes the next `todo` in its group to `next`, logs it. `--highways` defaults to the task area's highway.",
        "- `python scripts/roadmap.py log \"text\"`: new top log line and today's `updated`.",
        "- `python scripts/roadmap.py add-task <group> --area <area> --title \"...\" --note \"...\"`: appends a `todo` with the next id and patch version.",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------- edits (text-level, so diffs stay small)


def _task_span(text: str, task_id: str) -> tuple[int, int]:
    """Character range of one task's object, from its id line to the closing brace line."""
    m = re.search(rf'^( +)"id": "{re.escape(task_id)}",\n', text, re.M)
    if not m:
        raise SystemExit(f"roadmap: no task {task_id!r}")
    indent = m.group(1)
    end = re.compile(rf"^{indent[:-2]}\}}", re.M).search(text, m.end())
    return m.start(), end.start()


def _set_status(text: str, task_id: str, status: str) -> str:
    a, b = _task_span(text, task_id)
    block = re.sub(r'("status": )"[a-z]+"', rf'\1"{status}"', text[a:b], count=1)
    return text[:a] + block + text[b:]


def _set_refs_note(text: str, task_id: str, refs: list[str], note: str | None) -> str:
    a, b = _task_span(text, task_id)
    block = text[a:b]
    indent = re.match(r" +", block).group(0)
    if refs:
        body = ",\n".join(f'{indent}  {json.dumps(r)}' for r in refs)
        new = f'{indent}"refs": [\n{body}\n{indent}],\n'
        if re.search(r'^ +"refs": \[.*?^ +\],\n', block, re.M | re.S):
            block = re.sub(r'^ +"refs": \[.*?^ +\],\n', lambda _: new, block, count=1, flags=re.M | re.S)
        else:
            block = re.sub(r'(^ +"stories": \[.*?\],\n)', lambda m: m.group(1) + new, block, count=1, flags=re.M | re.S)
    if note is not None:
        line = f'{indent}"notes": {json.dumps(note, ensure_ascii=False)}\n'
        if re.search(r'^ +"notes": .*\n', block, re.M):
            block = re.sub(r'^ +"notes": .*\n', lambda _: line, block, count=1, flags=re.M)
        else:
            block = re.sub(r",?\n$", ",\n", block) + line
    return text[:a] + block + text[b:]


def _add_log(text: str, line: str, today: str) -> str:
    entry = f'    {{\n      "date": "{today}",\n      "text": {json.dumps(line, ensure_ascii=False)}\n    }},\n'
    text = text.replace('"log": [\n', '"log": [\n' + entry, 1)
    return re.sub(r'^(  "updated": )"[\d-]+"', rf'\1"{today}"', text, count=1, flags=re.M)


def _add_release(text: str, version: str, title: str, highways: list[str], sentence: str, today: str) -> str:
    hw = ", ".join(json.dumps(h) for h in highways)
    entry = (f'    {{\n      "version": "{version}",\n      "status": "released",\n      "date": "{today}",\n'
             f'      "title": {json.dumps(title, ensure_ascii=False)},\n      "highways": [{hw}],\n'
             f'      "text": {json.dumps(sentence, ensure_ascii=False)}\n    }},\n')
    starts = [(m.start(), m.group(1)) for m in re.finditer(r'^    \{\n      "version": "([\d.]+)",', text, re.M)]
    later = next((pos for pos, v in starts if vkey(v) > vkey(version)), None)
    if later is None:
        raise SystemExit("roadmap: no later release to insert before; edit roadmap.js by hand")
    return text[:later] + entry + text[later:]


def _find(data: dict, task_id: str) -> tuple[dict, dict]:
    for m in data["milestones"]:
        for t in m["tasks"]:
            if t["id"] == task_id:
                return m, t
    raise SystemExit(f"roadmap: no task {task_id!r}")


def apply(edit, path: Path = ROADMAP) -> int:
    """Run `edit(text, data) -> new text`, validate, and keep the result only if the roadmap still checks out."""
    original = path.read_text(encoding="utf-8")
    new = edit(original, load(path))
    path.write_text(new, encoding="utf-8")
    errors = check(load(path)) if _loads(path) else ["roadmap.js no longer parses"]
    if errors:
        path.write_text(original, encoding="utf-8")
        print("roadmap: edit rejected and undone:")
        for e in errors:
            print(f"  {e}")
        return 1
    return 0


def _loads(path: Path) -> bool:
    try:
        load(path)
        return True
    except ValueError:
        return False


def cmd_start(a, path: Path, today: str) -> int:
    def edit(text, data):
        _find(data, a.task)
        text = _set_status(text, a.task, "doing")
        return _add_log(text, f"Started {a.task}.", today)
    return apply(edit, path)


def cmd_done(a, path: Path, today: str) -> int:
    def edit(text, data):
        group, task = _find(data, a.task)
        hw = a.highways.split(",") if a.highways else [h["id"] for h in data["highways"] if task["area"] in h["areas"]]
        text = _set_status(text, a.task, "done")
        text = _set_refs_note(text, a.task, [r for r in (a.refs or "").split(",") if r], a.note)
        text = _add_release(text, task["version"], a.title, hw, a.text, today)
        waiting = [t for t in group["tasks"] if t["status"] == "todo" and t["id"] != a.task]
        if waiting and not any(t["status"] in ("doing", "next") for t in group["tasks"] if t["id"] != a.task):
            first = min(waiting, key=lambda t: vkey(t["version"]))
            text = _set_status(text, first["id"], "next")
        return _add_log(text, f"Released {task['version']}: {a.text}", today)
    return apply(edit, path)


def cmd_log(a, path: Path, today: str) -> int:
    return apply(lambda text, data: _add_log(text, a.text, today), path)


def cmd_add_task(a, path: Path, today: str) -> int:
    def edit(text, data):
        group = next((m for m in data["milestones"] if m["id"] == a.group), None)
        if not group:
            raise SystemExit(f"roadmap: no group {a.group!r}")
        n = max(int(t["id"].split(".")[1]) for t in group["tasks"]) + 1
        v = max((vkey(t["version"]) for t in group["tasks"]), default=(0, 0, 0))
        version = f"{v[0]}.{v[1]}.{v[2] + 1}"
        task = (f'        {{\n          "id": "{a.group}.{n}",\n          "version": "{version}",\n'
                f'          "title": {json.dumps(a.title, ensure_ascii=False)},\n          "status": "todo",\n'
                f'          "area": {json.dumps(a.area)},\n          "stories": [],\n'
                f'          "notes": {json.dumps(a.note or "", ensure_ascii=False)}\n        }}')
        a_, b_ = _task_span(text, group["tasks"][-1]["id"])
        close = re.compile(r"^        \}", re.M).search(text, b_ - 12)
        end = close.end()
        text = text[:end] + ",\n" + task + text[end:]
        print(f"added {a.group}.{n} at version {version}")
        return _add_log(text, f"Added task {a.group}.{n} ({version}): {a.title}", today)
    return apply(edit, path)


def main(argv: list[str] | None = None, path: Path = ROADMAP, today: str | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")  # the Windows console defaults to cp1252
    today = today or date.today().isoformat()
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("brief")
    s = sub.add_parser("start"); s.add_argument("task")
    d = sub.add_parser("done"); d.add_argument("task")
    d.add_argument("--title", required=True); d.add_argument("--text", required=True)
    d.add_argument("--highways"); d.add_argument("--refs"); d.add_argument("--note")
    lg = sub.add_parser("log"); lg.add_argument("text")
    at = sub.add_parser("add-task"); at.add_argument("group")
    at.add_argument("--area", required=True); at.add_argument("--title", required=True); at.add_argument("--note")
    a = p.parse_args(argv)
    if a.cmd == "brief":
        out = build_brief(load(path))
        path.with_name("roadmap-brief.md").write_text(out, encoding="utf-8")
        print(out)
        return 0
    code = {"start": cmd_start, "done": cmd_done, "log": cmd_log, "add-task": cmd_add_task}[a.cmd](a, path, today)
    if code == 0:
        print("roadmap ok" if not check(load(path)) else "roadmap: check failed")
    return code


if __name__ == "__main__":
    sys.exit(main())
