"""Roadmap: releases are destinations; task completion is progress, not shipping.

python scripts/roadmap.py brief --level minimal|medium|maximum
python scripts/roadmap.py add-task 2.0.0 --area dll --title "..."
python scripts/roadmap.py start TASK_ID
python scripts/roadmap.py done TASK_ID --refs FILE,BRANCH --note "Checked ..."
python scripts/roadmap.py move TASK_ID --before OTHER_ID
python scripts/roadmap.py retarget TASK_ID 2.1.0
python scripts/roadmap.py release VERSION --validated "Checks passed ..."
python scripts/roadmap.py release VERSION --tasks ID,ID --title "..." --text "One sentence." --validated "..."

Edits validate before writing. No command creates tags or pushes Git changes.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date
from pathlib import Path

from check_roadmap import ROADMAP, check, load, tier, vkey

BRIEF_LEVELS = ("minimal", "medium", "maximum")
IN_PROGRESS = ("doing", "next", "blocked")
RECENT_COMPLETIONS = 5


def _find(data: dict, task_id: str) -> dict:
    task = next((t for t in data["tasks"] if t["id"] == task_id), None)
    if task is None: raise ValueError(f"no task {task_id!r}")
    return task


def _release(data: dict, version: str) -> dict:
    release = next((r for r in data["releases"] if r["version"] == version), None)
    if release is None: raise ValueError(f"no release {version!r}")
    return release


def _future(data: dict, version: str) -> dict:
    release = _release(data, version)
    if release["status"] == "released": raise ValueError("cannot add or retarget work to a shipped destination")
    return release


def _log(data: dict, text: str, today: str) -> None:
    if not text.strip(): raise ValueError("log text cannot be empty")
    data["updated"] = today
    data["log"].insert(0, {"date": today, "text": text})


def build_brief(data: dict) -> str:
    return build_full_brief(data, "minimal")


def build_full_brief(data: dict, level: str) -> str:
    if level not in BRIEF_LEVELS: raise ValueError(f"unknown brief level {level}")
    lines = [f"# Completionist roadmap brief — {level}", "",
             "Generated by `python scripts/roadmap.py brief`. Do not edit or commit.", "",
             "## Use cases", "",
             "- **Minimal**: current work with target release, status, area and optional stage.",
             "- **Medium**: current goals and remaining work, recent completions and five recently shipped releases.",
             "- **Maximum**: full JSON including every task, release, plan, reference and historical log.", "",
             "**Avoid opening `docs/roadmap/roadmap.js`** for routine work; use `start`, `done`, `add-task`, `move`, `retarget`, `release` and `log`.", ""]
    if level == "maximum":
        return "\n".join(lines + ["## Complete roadmap data", "", "```json", json.dumps(data, ensure_ascii=False, indent=2), "```", ""])
    released = sorted((r for r in data["releases"] if r["status"] == "released"), key=lambda r: vkey(r["version"]), reverse=True)
    latest = released[0]["version"] if released else "none"
    lines += [f"Updated {data['updated']}. Latest shipped version: **{latest}**. Active target: **{data.get('activeRelease') or 'none'}**.", "", "## In progress", ""]

    def task_line(t: dict) -> None:
        stages = [x for x in data["tasks"] if x["targetRelease"] == t["targetRelease"] and x.get("stage")]
        stage = f" · stage {t['stage']}/{max(x['stage'] for x in stages)}" if t.get("stage") else ""
        shipped = f" · shipped in {t['shippedIn']}" if t.get("shippedIn") else " · not yet shipped" if t["status"] == "done" else ""
        lines.append(f"- [{t['status']}] {t['id']} · target {t['targetRelease']}{stage} · {t['area']}{shipped} · {t['title']}")
        if level == "medium" and t.get("notes"): lines.append("  " + " ".join(t["notes"].split()))

    found = False
    for r in data["releases"]:
        work = [t for t in data["tasks"] if t["targetRelease"] == r["version"]]
        visible = [t for t in work if t["status"] in IN_PROGRESS or (level == "medium" and t["status"] == "todo" and r["version"] == data.get("activeRelease"))]
        if not visible: continue
        found = True; plan = data["releasePlans"].get(r["version"], {})
        lines += [f"### {r['version']} · {plan.get('title', r['title'])}", ""]
        if level == "medium": lines += [f"Goal: {plan.get('goal', r['title'])}", f"Ready when: {plan.get('done_when', 'Validated for release.')}", ""]
        for t in visible: task_line(t)
        lines.append("")
    if not found: lines += ["No current tasks.", ""]
    if level == "medium":
        completed = sorted((t for t in data["tasks"] if t["status"] == "done" and t.get("completed")), key=lambda t: t["completed"], reverse=True)[:RECENT_COMPLETIONS]
        lines += ["## Recently completed work", "", "Completion is separate from shipping.", ""]
        for t in completed: task_line(t)
        if not completed: lines += ["No completion dates recorded yet; historical shipping remains below."]
        lines += ["", "## Recently shipped releases", ""]
        for r in released[:RECENT_COMPLETIONS]:
            lines += [f"### {r['version']} · {r['title']} · {r.get('date', 'undated')}", ""]
            for p in r.get("essay", [r.get("text", "")]): lines += [p, ""]
            for t in data["tasks"]:
                if t.get("shippedIn") == r["version"]: task_line(t)
            lines.append("")
    return "\n".join(lines) + "\n"


def _edit(data: dict, args: argparse.Namespace, today: str) -> str:
    if args.cmd == "log": _log(data, args.text, today); return "Logged roadmap update."
    if args.cmd == "add-task":
        _future(data, args.release)
        slug = re.sub(r"[^a-z0-9]+", "-", args.title.lower()).strip("-") or "task"
        task_id = args.id or slug
        ids = {t["id"] for t in data["tasks"]}; suffix = 2
        if args.id and task_id in ids: raise ValueError("task id already exists")
        while task_id in ids: task_id = f"{slug}-{suffix}"; suffix += 1
        task = {"id": task_id, "targetRelease": args.release, "title": args.title,
                "status": "todo", "area": args.area, "stories": args.stories or [], "notes": args.note or ""}
        if args.label: task["label"] = args.label
        if args.stage is not None: task["stage"] = args.stage
        if args.before:
            other = _find(data, args.before)
            if other["targetRelease"] != args.release: raise ValueError("--before task must have the same target")
            data["tasks"].insert(data["tasks"].index(other), task)
        else:
            matching = [i for i,t in enumerate(data["tasks"]) if t["targetRelease"] == args.release]
            data["tasks"].insert(matching[-1]+1 if matching else len(data["tasks"]), task)
        _log(data, f"Added task {task_id} toward {args.release}: {args.title}", today)
        return f"added {task_id} toward {args.release}"
    if args.cmd in {"start", "done", "move", "retarget", "drop"}:
        task = _find(data, args.task)
        if args.cmd in {"start", "drop", "retarget"} and (task.get("shippedIn") or task["status"] in {"done", "dropped"}):
            raise ValueError("completed or dropped work is historical; add a new task instead")
        if args.cmd == "start":
            if task["status"] == "dropped": raise ValueError("cannot start dropped work; add a new task")
            task["status"] = "doing"; message = f"Started {args.task} toward {task['targetRelease']}."
        elif args.cmd == "done":
            if task["status"] in {"done", "dropped"}: raise ValueError("task is already done or dropped")
            task["status"] = "done"; task["completed"] = today
            if args.refs: task["refs"] = list(dict.fromkeys(task.get("refs", []) + [s.strip() for s in args.refs.split(",") if s.strip()]))
            if args.note is not None: task["notes"] = args.note
            pending = [t for t in data["tasks"] if t["targetRelease"] == task["targetRelease"]]
            if not any(t["status"] in {"doing", "next"} for t in pending):
                first = next((t for t in pending if t["status"] == "todo"), None)
                if first: first["status"] = "next"
            message = f"Completed {args.task} toward {task['targetRelease']}; no release was created."
        elif args.cmd == "drop":
            task["status"] = "dropped"
            if args.reason: task["notes"] = (task.get("notes", "") + "\nDropped: " + args.reason).strip()
            message = f"Dropped {args.task}: {args.reason}"
        elif args.cmd == "move":
            other = _find(data, args.before)
            if other is task: raise ValueError("cannot move a task before itself")
            if other["targetRelease"] != task["targetRelease"]: raise ValueError("move only reorders within a target; use retarget to change destination")
            if task["status"] in {"done", "dropped"}: raise ValueError("move only reorders unfinished work")
            data["tasks"].remove(task); data["tasks"].insert(data["tasks"].index(other), task)
            message = f"Moved {args.task} before {args.before} without renumbering."
        else:
            _future(data, args.release); old = task["targetRelease"]
            task["targetRelease"] = args.release
            task.pop("stage", None)
            message = f"Retargeted {args.task} from {old} to {args.release}."
        _log(data, message, today); return message
    if args.cmd == "release":
        if not args.validated.strip(): raise ValueError("release requires a validation statement")
        existing = next((r for r in data["releases"] if r["version"] == args.version), None)
        if existing and existing["status"] == "released": raise ValueError("release already shipped; history is immutable")
        chosen = [_find(data, s.strip()) for s in args.tasks.split(",") if s.strip()] if args.tasks else [t for t in data["tasks"] if t["targetRelease"] == args.version and t["status"] != "dropped"]
        if not chosen or any(t["status"] != "done" for t in chosen): raise ValueError("cannot release unfinished or empty work")
        if existing and any(t["targetRelease"] == args.version and t["status"] not in {"done", "dropped"} for t in data["tasks"]):
            raise ValueError("destination still has unfinished work")
        if not existing and any(t.get("shippedIn") for t in chosen): raise ValueError("a new patch must include unshipped completed tasks")
        if not existing and (not args.title or not args.text or not vkey(args.version)[2]):
            raise ValueError("new releases must be concrete patches with --tasks, --title and --text; plan major/minor destinations first")
        released = [r for r in data["releases"] if r["status"] == "released"]
        if released and vkey(args.version) <= max(vkey(r["version"]) for r in released): raise ValueError("a new release must follow the latest shipped version")
        release = existing or {"version": args.version, "title": args.title, "text": args.text}
        release.update(status="released", date=today, validation=args.validated)
        if args.text is not None: release["text"] = args.text
        if args.essay_file: release["essay"] = [p.strip() for p in Path(args.essay_file).read_text(encoding="utf-8").split("\n\n") if p.strip()]
        if args.title: release["title"] = args.title
        areas = {t["area"] for t in chosen}
        release["highways"] = [h["id"] for h in data["highways"] if areas.intersection(h["areas"])]
        if args.fix: release["kind"] = "fix"
        if not existing: data["releases"].append(release)
        for t in chosen:
            if not t.get("shippedIn"): t["shippedIn"] = args.version
        data["releases"].sort(key=lambda r: vkey(r["version"]))
        if data.get("activeRelease") == args.version:
            future = next((r for r in data["releases"] if r["status"] != "released" and r["version"] in data["releasePlans"]), None)
            data["activeRelease"] = future["version"] if future else None
            if future: future["status"] = "next"
        _log(data, f"Released {args.version} after validation: {args.validated}", today)
        return f"Recorded release {args.version}; tag and publish separately."
    raise ValueError(f"unknown command {args.cmd}")


def main(argv: list[str] | None = None, path: Path = ROADMAP, today: str | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"): sys.stdout.reconfigure(encoding="utf-8")
    today = today or date.today().isoformat()
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    brief = sub.add_parser("brief"); brief.add_argument("--level", choices=("session", *BRIEF_LEVELS), default="minimal")
    start = sub.add_parser("start"); start.add_argument("task")
    done = sub.add_parser("done"); done.add_argument("task"); done.add_argument("--refs"); done.add_argument("--note")
    log = sub.add_parser("log"); log.add_argument("text")
    add = sub.add_parser("add-task"); add.add_argument("release"); add.add_argument("--id"); add.add_argument("--area", required=True); add.add_argument("--title", required=True)
    add.add_argument("--note"); add.add_argument("--label"); add.add_argument("--stage", type=int); add.add_argument("--before"); add.add_argument("--stories", type=int, nargs="*")
    move = sub.add_parser("move"); move.add_argument("task"); move.add_argument("--before", required=True)
    retarget = sub.add_parser("retarget"); retarget.add_argument("task"); retarget.add_argument("release")
    drop = sub.add_parser("drop"); drop.add_argument("task"); drop.add_argument("--reason", required=True)
    release = sub.add_parser("release"); release.add_argument("version"); release.add_argument("--tasks"); release.add_argument("--title"); release.add_argument("--text")
    release.add_argument("--essay-file"); release.add_argument("--validated", required=True); release.add_argument("--fix", action="store_true")
    args = parser.parse_args(argv)
    try:
        data = load(path)
        initial_errors = check(data)
        if initial_errors: raise ValueError("source is invalid: " + "; ".join(initial_errors))
        if args.cmd == "brief":
            outputs = {level: build_full_brief(data, level) for level in BRIEF_LEVELS}
            for level, output in outputs.items(): path.with_name(f"roadmap-brief-{level}.md").write_text(output, encoding="utf-8")
            path.with_name("roadmap-brief.md").write_text(outputs["minimal"], encoding="utf-8")
            print(outputs["minimal" if args.level == "session" else args.level], end=""); return 0
        message = _edit(data, args, today)
        errors = check(data)
        if errors: raise ValueError("edit rejected: " + "; ".join(errors))
        path.write_text("window.COMPLETIONIST_ROADMAP = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
        print(message); print("roadmap ok"); return 0
    except (OSError, ValueError, KeyError) as exc:
        print(f"roadmap: {exc}"); return 1


if __name__ == "__main__": sys.exit(main())
